CREATE TABLE IF NOT EXISTS Book(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    author INT NOT NULL,
    genre INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Author(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    second_name VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS Genre(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL
);

ALTER TABLE public.BOOK
    ADD FOREIGN KEY (author)
    REFERENCES public.AUTHOR(id);

ALTER TABLE public.BOOK
    ADD FOREIGN KEY (genre)
    REFERENCES public.GENRE(id);